// 全局css
import './global.css'

export const metadata = {
  title: 'Next.js - basic',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
